//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 10:34:02 PM EEST 
//


package com.usdgadget.movies;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://usdgadget.com/movies}Status"/>
 *         &lt;element name="MovieDetails" type="{http://usdgadget.com/movies}MovieDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "movieDetails"
})
@XmlRootElement(name = "AddMovieDetailsResponse")
public class AddMovieDetailsResponse {

    @XmlElement(name = "Status", required = true)
    protected Status status;
    @XmlElement(name = "MovieDetails", required = true)
    protected MovieDetails movieDetails;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the movieDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MovieDetails }
     *     
     */
    public MovieDetails getMovieDetails() {
        return movieDetails;
    }

    /**
     * Sets the value of the movieDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MovieDetails }
     *     
     */
    public void setMovieDetails(MovieDetails value) {
        this.movieDetails = value;
    }

}
