//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 10:34:02 PM EEST 
//


package com.usdgadget.movies;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.usdgadget.movies package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.usdgadget.movies
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddMovieDetailsRequest }
     * 
     */
    public AddMovieDetailsRequest createAddMovieDetailsRequest() {
        return new AddMovieDetailsRequest();
    }

    /**
     * Create an instance of {@link GetMovieDetailsRequest }
     * 
     */
    public GetMovieDetailsRequest createGetMovieDetailsRequest() {
        return new GetMovieDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteMovieDetailsResponse }
     * 
     */
    public DeleteMovieDetailsResponse createDeleteMovieDetailsResponse() {
        return new DeleteMovieDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteMovieDetailsRequest }
     * 
     */
    public DeleteMovieDetailsRequest createDeleteMovieDetailsRequest() {
        return new DeleteMovieDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllMovieDetailsResponse }
     * 
     */
    public GetAllMovieDetailsResponse createGetAllMovieDetailsResponse() {
        return new GetAllMovieDetailsResponse();
    }

    /**
     * Create an instance of {@link MovieDetails }
     * 
     */
    public MovieDetails createMovieDetails() {
        return new MovieDetails();
    }

    /**
     * Create an instance of {@link GetAllMovieDetailsRequest }
     * 
     */
    public GetAllMovieDetailsRequest createGetAllMovieDetailsRequest() {
        return new GetAllMovieDetailsRequest();
    }

    /**
     * Create an instance of {@link AddMovieDetailsResponse }
     * 
     */
    public AddMovieDetailsResponse createAddMovieDetailsResponse() {
        return new AddMovieDetailsResponse();
    }

    /**
     * Create an instance of {@link GetMovieDetailsResponse }
     * 
     */
    public GetMovieDetailsResponse createGetMovieDetailsResponse() {
        return new GetMovieDetailsResponse();
    }

}
